inherit_from:
  - '.rubocop_core.yml'
  - '.rubocop_performance.yml'
  - '.rubocop_rails.yml'
  - '.rubocop_rspec.yml'
  - '.rubocop_local.yml'

# Put your project-specific Rubocop configuration in .rubocop_local.yml
