# Last updated to 1.5.0

require:
  - 'rubocop-performance'

################################################################################
#                                PERFORMANCE
################################################################################

Performance/Caller:
  Enabled:                                    true

Performance/Casecmp:
  Enabled:                                    true

Performance/CaseWhenSplat:
  Enabled:                                    true

Performance/ChainArrayAllocation:
  Enabled:                                    true

Performance/CompareWithBlock:
  Enabled:                                    true

Performance/Count:
  Enabled:                                    true

Performance/Detect:
  Enabled:                                    true

Performance/DoubleStartEndWith:
  Enabled:                                    true
  IncludeActiveSupportAliases:                true

Performance/EndWith:
  Enabled:                                    true

Performance/FixedSize:
  Enabled:                                    true

Performance/FlatMap:
  Enabled:                                    true

Performance/InefficientHashSearch:
  Enabled:                                    true

Performance/OpenStruct:
  Enabled:                                    true
  Exclude:
    - '**/spec/**/*.rb'

Performance/RangeInclude:
  Enabled:                                    true

Performance/RedundantBlockCall:
  Enabled:                                    true

Performance/RedundantMatch:
  Enabled:                                    true

Performance/RedundantMerge:
  Enabled:                                    true

Performance/RegexpMatch:
  Enabled:                                    true

Performance/ReverseEach:
  Enabled:                                    true

Performance/Size:
  Enabled:                                    true

Performance/StartWith:
  Enabled:                                    true

Performance/StringReplacement:
  Enabled:                                    true

Performance/TimesMap:
  Enabled:                                    true
  AutoCorrect:                                true

Performance/UnfreezeString:
  Enabled:                                    true

Performance/UriDefaultParser:
  Enabled:                                    true
